Check valid profile, switch to log output, bug fix

diff --git a/bashdot b/bashdot
--- a/bashdot
+++ b/bashdot
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-VERSION=2.0.0
+VERSION=2.1.0
 
 current_working_dir=`pwd`
 bashdot_config_file=$HOME/.bashdot
 
+LOGGER_FMT=${LOGGER_FMT:="%Y-%m-%d"}
+LOGGER_LVL=${LOGGER_LVL:="info"}
+
+if [ ! -z $BASHDOT_LOG_LEVEL ]; then
+    LOGGER_LVL=$BASHDOT_LOG_LEVEL
+fi
+    
 # Files will not be symlinked by bashdot
 ignored_files="README.md"
 
@@ -34,6 +41,28 @@ if [ "$action" != "dir" ] &&
     exit 1
 fi
 
+function exit_if_invalid_profile_name() {
+    profile=$1
+    echo $profile | grep "^[a-zA-Z0-9_-]*$"
+    if [ $? -ne 0 ]; then
+        log error "Invalid profile name '$profile'. Profiles must be alpha number with dashes or underscores."
+        exit 1
+    fi
+}
+
+function log {
+    action=$1 && shift
+
+    case $action in
+        debug)  [[ $LOGGER_LVL =~ debug ]]           && echo "$( date "+${LOGGER_FMT}" ) - DEBUG - $@" 1>&2 ;;
+        info)   [[ $LOGGER_LVL =~ debug|info ]]      && echo "$( date "+${LOGGER_FMT}" ) - INFO - $@" 1>&2  ;;
+        warn)   [[ $LOGGER_LVL =~ debug|info|warn ]] && echo "$( date "+${LOGGER_FMT}" ) - WARN - $@" 1>&2  ;;
+        error)  [[ ! $LOGGER_LVL =~ none ]]          && echo "$( date "+${LOGGER_FMT}" ) - ERROR - $@" 1>&2 ;;
+    esac
+
+    true
+}
+
 install() {
     profile=$1
     profiles_dir=$current_working_dir/profiles
@@ -41,18 +70,18 @@ install() {
 
 
     if [ ! -d $profiles_dir ]; then
-        echo "Directory profiles does not exist in '$current_working_dir'."
+        log error "Directory profiles does not exist in '$current_working_dir'."
         exit 1
     fi
 
     if [ ! -d $profile_dir ]; then
-        echo "Profile '$profile' directory does not exist."
+        log error "Profile '$profile' directory does not exist."
         exit 1
     fi
 
-    echo "Adding dotfiles profile '$profile'."
+    log info "Adding dotfiles profile '$profile'."
 
-    echo "Checking for exiting dotfiles."
+    log debug "Checking for exiting dotfiles."
     cd $profile_dir
     for file in `ls |grep -v $ignored_files`; do
         dotfile=~/.$file
@@ -65,38 +94,38 @@ install() {
                 continue
             fi
 
-            echo "File '$dotfile' already exists, exiting."
+            log error "File '$dotfile' already exists, exiting."
             exit 1
         fi
     done
-    echo "Found no existing dotfiles in home."
+    log debug "Found no existing dotfiles in home."
 
     if [ -f $bashdot_config_file ]; then
-        grep $current_working_dir $bashdot_config_file > /dev/null
+        egrep "^$current_working_dir$" $bashdot_config_file > /dev/null
 
         if [ $? -ne 0 ]; then
-            echo "Appending bashdot '$current_working_dir' to '$bashdot_config_file'"
+            log debug "Appending bashdot '$current_working_dir' to '$bashdot_config_file'"
             echo $current_working_dir >> $bashdot_config_file
         fi
     else
         echo $current_working_dir > $bashdot_config_file
     fi
 
-    echo "Installing dotfiles from '$profiles_dir'."
+    log info "Installing dotfiles from '$profiles_dir'."
     for file in `ls |grep -v $ignored_files`; do
         dotfile=~/.$file
         source_file=$profile_dir/$file
         existing=`readlink $dotfile`
 
         if [ "$existing" == "$source_file" ]; then
-            echo "File '$dotfile' is the same, continuing."
+            log debug "File '$dotfile' is the same, continuing."
             continue
         fi
-        echo "Linking '$source_file' to '$dotfile'."
+        log info "Linking '$source_file' to '$dotfile'."
         ln -s $source_file $dotfile
     done
 
-    echo "Completed adding dotfiles profile '$profile'."
+    log info "Completed adding dotfiles profile '$profile'."
 }
 
 list_links() {
@@ -107,7 +136,7 @@ list_links() {
 
             # Only include if it points to the dotfiles directory
             for bashdot_dir in $(cat $bashdot_config_file); do
-                readlink ~/$i |grep $bashdot_dir > /dev/null
+                readlink ~/$i |egrep "^$bashdot_dir/profiles" > /dev/null
                 if [ $? -eq 0 ];then
                     echo $i
                 fi
@@ -118,11 +147,11 @@ list_links() {
 
 list_profiles() {
     if [ ! -f $bashdot_config_file ];then
-        echo "No dotfiles installed by bashdot."
+        log info "No dotfiles installed by bashdot."
     else
         for dir in $(cat $bashdot_config_file); do
             for link in $(list_links); do
-                readlink ~/$link | grep $dir > /dev/null
+                readlink ~/$link | egrep "^$dir/profiles" > /dev/null
                 if [ $? -eq 0 ]; then
                     profile=`readlink ~/$link |sed -e "s/^.*\/profiles\/\(.*\)\/.*$/\1/"`
                     echo "$dir $profile"
@@ -142,7 +171,7 @@ show_links() {
 
 dir() {
     if [ ! -f $bashdot_config_file ];then
-        echo "No dotfiles installed by bashdot."
+        log info "No dotfiles installed by bashdot."
     else
         cat $bashdot_config_file |sort
     fi
@@ -153,15 +182,15 @@ uninstall() {
     profile=$2
 
     if [ ! -f $bashdot_config_file ]; then
-        echo "Config file '$bashdot_config_file' not found."
-        echo "No dotfiles installed by bashdot."
+        log error "Config file '$bashdot_config_file' not found."
+        log error "No dotfiles installed by bashdot."
         exit 1
     fi
 
     # Don't proceed with uninstall if profiles not available in given directory
     list_profiles |grep "^$dir $profile$"
     if [ $? -ne 0 ];then
-        echo "Profile '$profile' not installed from '$dir'."
+        log error "Profile '$profile' not installed from '$dir'."
         exit 1
     fi
 
@@ -170,7 +199,7 @@ uninstall() {
     for link in $(list_links);do
         echo `readlink ~/$link` |grep ^$dir/profiles/$profile > /dev/null
         if [ $? -eq 0 ]; then
-            echo "Removing '$link'."
+            log info "Removing '$link'."
             \rm ~/$link
         fi
     done
@@ -185,7 +214,7 @@ uninstall() {
     done
 
     if [ "$dir_empty" = true ]; then
-        echo "Removing '$dir' from '$bashdot_config_file'."
+        log info "Removing '$dir' from '$bashdot_config_file'."
         mv $bashdot_config_file ${bashdot_config_file}.backup
         cat ${bashdot_config_file}.backup |grep -v "^$dir$" > $bashdot_config_file
     fi
@@ -213,10 +242,11 @@ case $action in
                 break
             fi
 
+            exit_if_invalid_profile_name $1
             install $1
         done
 
-        echo "Completed installation of all profiles succesfully."
+        log info "Completed installation of all profiles succesfully."
         ;;
     links)
         show_links
@@ -230,7 +260,7 @@ case $action in
             exit 1
         fi
         uninstall $2 $3
-        echo "Completed uninstallation succesfully."
+        log info "Completed uninstallation succesfully."
         ;;
     version)
         echo $VERSION
